# Generated by Django 3.0.6 on 2020-05-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20200525_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
