# Generated by Django 3.0.6 on 2020-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_auto_20200526_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('O+', 'O-'), ('AB+', 'AB-')], max_length=5, null=True),
        ),
    ]
