# Generated by Django 3.0.6 on 2020-05-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_patient_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priscription', models.CharField(blank=True, max_length=500, null=True)),
                ('desease', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patient')),
            ],
        ),
    ]
