# Generated by Django 3.0.6 on 2020-05-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_auto_20200527_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
