# Generated by Django 3.0.6 on 2020-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_doctor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
